name: Test Dispatcher

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string  
        description: The env to use

jobs:
  test_dispatcher:
    name: Test Dispatcher
    uses: JaydipZala/Hello-Wolrd/.github/workflows/test.yml@main
    with:
      environment: ${{ github.event.inputs.environment }}
