name: Test

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string  
        description: The env to use

jobs:
  env:
    outputs:
      runner: ${{ steps.set_runner.outputs.runner }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "environment: ${{ github.event.inputs.environment }}"
