name: workflow1_1
on: 
  workflow_dispatch:
    inputs:
      workflow:
        required: true
        type: string
        description: "Workflow to dispatch next (workflow2-dispatch, workflow3-dispatch)"
        default: 'workflow3-dispatch'
  repository_dispatch:
    types: workflow1-dispatch

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.ACTION_SECRET }}" \
            https://api.github.com/repos/JaydipZala/Hello-World/actions/workflows/53948520/dispatches \
            -d '{"ref":"main", "inputs": {"flavor":"dev"}}'
