name: workflow1
on: 
  workflow_dispatch:
    inputs:
      workflow:
        required: true
        type: string
        description: "Workflow to dispatch next (workflow2-dispatch, workflow3-dispatch)"
        default: 'workflow3-dispatch'
  repository_dispatch:
    types: workflow1-dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.ACTION_SECRET }}" \
            https://api.github.com/repos/:owner/:repo/actions/workflows/:workflow_id/dispatches \
            -d '{"ref":"main", "inputs": {"my_input":"my_value"}}'
      - uses: actions/checkout@v3
