name: workflow1
on: 
  workflow_dispatch:
    inputs:
      workflow:
        required: true
        type: string
        description: "Workflow to dispatch next (workflow2-dispatch, workflow3-dispatch)"
        default: 'workflow3-dispatch'
  repository_dispatch:
    types: workflow1-dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/JaydipZala/Hello-World/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTION_SECRET }} \
          --data '{"event_type": "${{ github.event.inputs.workflow }}", "client_payload": { "message": "job successful", "flavor": "dev" } }'
          -d '{"ref":"main", "inputs": {"flavor":"dev"}}'
      - uses: actions/checkout@v3
