name: workflow1_2
on: 
  repository_dispatch:
    types: workflow1-dispatch

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Triggering workflow2
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.ACTION_SECRET }}" \
            https://api.github.com/repos/JaydipZala/Hello-World/actions/workflows/53947030/dispatches \
            -d '{"ref":"main", "inputs": {"flavor":"qa"}}'
      - name: Triggering workflow3
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.ACTION_SECRET }}" \
            https://api.github.com/repos/JaydipZala/Hello-World/actions/workflows/53948520/dispatches \
            -d '{"ref":"main", "inputs": {"flavor":"dev"}}'
