name: workflow1_1
on: 
  workflow_dispatch:
    inputs:
      workflow:
        required: true
        type: string
        description: "Workflow id to dispatch next (workflow2-dispatch / 53947030, workflow3-dispatch / 53948520)"
        default: '53948520'
  repository_dispatch:
    types: workflow1-dispatch

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.ACTION_SECRET }}" \
            "https://api.github.com/repos/JaydipZala/Hello-World/actions/workflows/${{ github.event.inputs.workflow }}/dispatches" \
            -d '{"ref":"main", "inputs": {"flavor":"dev"}}'
