name: workflow1
on: 
  repository_dispatch:
    types: workflow1-dispactch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/JaydipZala/Hello-World/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTION_SECRET }} \
          --data '{"event_type": "workflow2-dispatch", "client_payload": { "message": "job successful" } }'
      - uses: actions/checkout@v3
